name: stefanhoth
favicon: null
layout_spectrum: 0.76557
title: 'Stefan on software development, process and professionalism'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: f13cf2e2-fbbc-4163-a899-72cc53360dae
    url: null
